// @generated by schema-rust-next
use std::os::unix::net::UnixStream;
use thiserror::Error;
use triad_runtime::{
    ArgumentError, ComponentArgument, ComponentCommand, ConnectionContext,
    DaemonConfiguration, ExitReport, FrameBody, FrameError, LengthPrefixedCodec,
    ListenerError, ListenerSocket, MultiListenerDaemon, MultiListenerDaemonError,
    MultiListenerRuntime, RequestErrorLog, SocketMode,
};
use crate::schema::signal::{Input, Output, SignalFrameError};
/// The component hook surface for the emitted daemon — the only daemon
/// code the component hand-writes (record 1488 escape hatches).
///
/// The component declares its `Configuration` / `Engine` / `Error` types
/// and `PROCESS_NAME`, and provides the REQUIRED `build_runtime` (the
/// emitter cannot know how to open the component's Store/Engine) plus the
/// typed working-input handler. Streaming hooks are residual: when the
/// schema declares a stream the registry/publish plumbing is emitted, and
/// the component supplies only filter + event policy. The meta tier is the
/// owner-only escape hatch — the component owns its full read/handle/write.
pub trait ComponentDaemon: Sized + 'static {
    type Configuration: DaemonConfiguration;
    type ConfigurationError: std::error::Error;
    type Engine;
    type Error: std::fmt::Display
        + From<FrameError>
        + From<SignalFrameError>
        + From<ListenerError>;
    const PROCESS_NAME: &'static str;
    /// Load the binary rkyv `Configuration` from the daemon's single argument.
    fn load_configuration(
        path: &std::path::Path,
    ) -> Result<Self::Configuration, Self::ConfigurationError>;
    /// Open the component's durable Store and construct its Engine.
    fn build_runtime(
        configuration: &Self::Configuration,
    ) -> Result<Self::Engine, Self::Error>;
    /// Lifecycle: called once before the listener serves, once after it stops.
    fn start(engine: &mut Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    fn stop(engine: &mut Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    /// Run one decoded working `Input` through the engine and return the
    /// `Output` root to encode back to the caller.
    ///
    /// `connection` carries the accepted stream's kernel-vouched peer
    /// credentials (uid / gid / pid via `SO_PEERCRED`), so the component can
    /// mint an origin from the operating-system trust boundary rather than
    /// trusting a payload claim. Components that do not classify by origin
    /// take it as `_connection`.
    fn handle_working_input(
        engine: &Self::Engine,
        input: Input,
        connection: &triad_runtime::ConnectionContext,
    ) -> Result<Output, Self::Error>;
    /// Serve one owner-only meta stream end to end (read, handle, write).
    /// The meta wire codec is component-owned, so this is a full escape hatch.
    fn handle_meta_stream(
        engine: &Self::Engine,
        stream: UnixStream,
    ) -> Result<(), Self::Error>;
}
/// argv -> binary `Configuration` -> the bound daemon. The single-argument
/// rule: exactly one argument, a signal-encoded (rkyv) configuration file.
pub struct DaemonCommand<Daemon: ComponentDaemon> {
    command: ComponentCommand,
    daemon: std::marker::PhantomData<fn() -> Daemon>,
}
impl<Daemon: ComponentDaemon> DaemonCommand<Daemon> {
    pub fn from_environment() -> Self {
        Self {
            command: ComponentCommand::from_environment(),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn from_arguments<Arguments, Argument>(arguments: Arguments) -> Self
    where
        Arguments: IntoIterator<Item = Argument>,
        Argument: Into<String>,
    {
        Self {
            command: ComponentCommand::from_arguments(arguments),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn configuration(&self) -> Result<Daemon::Configuration, DaemonError<Daemon>> {
        match self.command.signal_file_argument()? {
            ComponentArgument::SignalFile(file) => {
                Daemon::load_configuration(file.as_path())
                    .map_err(DaemonError::Configuration)
            }
            ComponentArgument::InlineNota(_) | ComponentArgument::NotaFile(_) => {
                Err(DaemonError::Argument(ArgumentError::ExpectedSignalFile))
            }
        }
    }
    pub fn run(&self) -> Result<(), DaemonError<Daemon>> {
        Daemon::bind(self.configuration()?)?.run().map_err(DaemonError::from)
    }
}
/// The bound daemon constructor on the component trait: builds the engine,
/// selects the listener tiers (single vs multi from the schema shape), and
/// returns a runner the `DaemonCommand` drives. The component never writes
/// this by hand — it is emitted as a default method on `ComponentDaemon`.
pub trait DaemonBinder: ComponentDaemon {
    fn bind(
        configuration: Self::Configuration,
    ) -> Result<MultiListenerDaemon<GeneratedDaemonRuntime<Self>>, DaemonError<Self>> {
        let engine = Self::build_runtime(&configuration)
            .map_err(DaemonError::Component)?;
        let runtime = GeneratedDaemonRuntime::<Self>::new(engine);
        let mut sockets = vec![
            ListenerSocket::new(ListenerTier::Working, configuration.socket_path()
            .to_path_buf(),)
        ];
        if let Some(meta_socket_path) = configuration.meta_socket_path() {
            let socket_mode = configuration
                .meta_socket_mode()
                .unwrap_or_else(|| SocketMode::new(0o600));
            sockets
                .push(
                    ListenerSocket::new(
                            ListenerTier::Meta,
                            meta_socket_path.to_path_buf(),
                        )
                        .with_socket_mode(socket_mode),
                );
        }
        Ok(
            MultiListenerDaemon::new(
                sockets,
                runtime,
                RequestErrorLog::new(Self::PROCESS_NAME),
            ),
        )
    }
}
impl<Daemon: ComponentDaemon> DaemonBinder for Daemon {}
/// The working-tier wire transport over one accepted stream: a
/// length-prefixed envelope around the schema-emitted signal frame codec.
struct WorkingTransport {
    stream: UnixStream,
}
impl WorkingTransport {
    fn new(stream: UnixStream) -> Self {
        Self { stream }
    }
    fn read_frame(&mut self) -> Result<Vec<u8>, FrameError> {
        Ok(LengthPrefixedCodec::default().read_body(&mut self.stream)?.into_bytes())
    }
    fn write_frame(&mut self, frame: Vec<u8>) -> Result<(), FrameError> {
        use std::io::Write;
        LengthPrefixedCodec::default()
            .write_body(&mut self.stream, &FrameBody::new(frame))?;
        self.stream.flush()?;
        Ok(())
    }
}
/// The generated runtime struct that owns the engine and (option B) the
/// emitted subscription registry. Its `handle_stream` IS the decode ->
/// execute -> encode spine.
pub struct GeneratedDaemonRuntime<Daemon: ComponentDaemon> {
    engine: Daemon::Engine,
}
impl<Daemon: ComponentDaemon> GeneratedDaemonRuntime<Daemon> {
    fn new(engine: Daemon::Engine) -> Self {
        Self { engine }
    }
    fn handle_working_stream(&self, stream: UnixStream) -> Result<(), Daemon::Error> {
        let connection = ConnectionContext::from_stream(&stream)
            .map_err(FrameError::Io)?;
        let mut transport = WorkingTransport::new(stream);
        let frame = transport.read_frame()?;
        let (_route, input) = Input::decode_signal_frame(&frame)?;
        let output = Daemon::handle_working_input(&self.engine, input, &connection)?;
        transport.write_frame(output.encode_signal_frame()?)?;
        Ok(())
    }
}
/// Which authority-tiered socket an arriving stream belongs to.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ListenerTier {
    Working,
    Meta,
}
impl std::fmt::Display for ListenerTier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Working => formatter.write_str("working"),
            Self::Meta => formatter.write_str("meta"),
        }
    }
}
impl<Daemon: ComponentDaemon> MultiListenerRuntime for GeneratedDaemonRuntime<Daemon> {
    type Listener = ListenerTier;
    type StartError = Daemon::Error;
    type StopError = Daemon::Error;
    type RequestError = Daemon::Error;
    fn start(&mut self) -> Result<(), Self::StartError> {
        Daemon::start(&mut self.engine)
    }
    fn stop(&mut self) -> Result<(), Self::StopError> {
        Daemon::stop(&mut self.engine)
    }
    fn handle_stream(
        &mut self,
        listener: ListenerTier,
        stream: UnixStream,
    ) -> Result<(), Self::RequestError> {
        match listener {
            ListenerTier::Working => self.handle_working_stream(stream),
            ListenerTier::Meta => Daemon::handle_meta_stream(&self.engine, stream),
        }
    }
}
/// The emitted daemon error: argv, configuration, listener, and the
/// component error. The component's own error rides the `Component` arm.
#[derive(Debug, Error)]
pub enum DaemonError<Daemon: ComponentDaemon> {
    #[error("daemon argument error: {0}")]
    Argument(ArgumentError),
    #[error("daemon configuration error: {0}")]
    Configuration(Daemon::ConfigurationError),
    #[error("daemon listener error: {0}")]
    Listener(ListenerError),
    #[error("component error: {0}")]
    Component(Daemon::Error),
}
impl<Daemon: ComponentDaemon> From<ArgumentError> for DaemonError<Daemon> {
    fn from(error: ArgumentError) -> Self {
        Self::Argument(error)
    }
}
impl<
    Daemon: ComponentDaemon,
> From<MultiListenerDaemonError<Daemon::Error, Daemon::Error>> for DaemonError<Daemon> {
    fn from(error: MultiListenerDaemonError<Daemon::Error, Daemon::Error>) -> Self {
        match error {
            MultiListenerDaemonError::Listener(error) => Self::Listener(error),
            MultiListenerDaemonError::Start(error)
            | MultiListenerDaemonError::Stop(error) => Self::Component(error),
        }
    }
}
/// The component-agnostic exit body. The component's binary calls
/// `<SpiritDaemon as DaemonEntry>::run_to_exit_code()` from `fn main`.
pub trait DaemonEntry: ComponentDaemon {
    fn run_to_exit_code() -> std::process::ExitCode {
        ExitReport::new(Self::PROCESS_NAME)
            .from_result(DaemonCommand::<Self>::from_environment().run())
    }
}
impl<Daemon: ComponentDaemon> DaemonEntry for Daemon {}
