// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use crate::schema::signal::Input as SignalInput;
pub use crate::schema::signal::Output as SignalOutput;
pub use crate::schema::signal::SessionName as SessionName;
pub use crate::schema::signal::SessionRecord as SessionRecord;
pub use crate::schema::signal::SessionResolution as SessionResolution;
pub use crate::schema::signal::PromptPatternRegistration as PromptPatternRegistration;
pub use crate::schema::signal::InputGateLease as InputGateLease;
pub use crate::schema::signal::InjectionReceipt as InjectionReceipt;
pub use crate::schema::signal::TranscriptCapture as TranscriptCapture;
pub use crate::schema::signal::ErrorReport as ErrorReport;
pub use crate::schema::sema::WriteInput as SemaWriteInput;
pub use crate::schema::sema::ReadInput as SemaReadInput;
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
pub use crate::schema::sema::ReadOutput as SemaReadOutput;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

pub type SignalArrived = SignalInput;

pub type MetaArrived = SessionLifecycleCommand;

pub type SemaWriteCompleted = SemaWriteOutput;

pub type SemaReadCompleted = SemaReadOutput;

pub type EffectCompleted = NexusEffectResult;

pub type ReplyToSignal = SignalOutput;

pub type CommandSemaWrite = SemaWriteInput;

pub type CommandSemaRead = SemaReadInput;

pub type CommandEffect = NexusEffectCommand;

pub type Continue = NexusWork;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    MetaArrived(MetaArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SessionLifecycleCommand {
    CreateSession(CreateSession),
    RetireSession(RetireSession),
}

pub type CreateSession = SessionRecord;

pub type RetireSession = SessionName;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalCellCommand {
    StartSession(StartSession),
    RegisterPromptPattern(RegisterPromptPattern),
    AcquireInputGate(AcquireInputGate),
    WriteInjection(WriteInjection),
    ReleaseInputGate(ReleaseInputGate),
    CaptureTranscript(CaptureTranscript),
}

pub type StartSession = SessionRecord;

pub type RegisterPromptPattern = SessionName;

pub type AcquireInputGate = SessionName;

pub type WriteInjection = SessionName;

pub type ReleaseInputGate = SessionName;

pub type CaptureTranscript = SessionName;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    RunTerminalCell(RunTerminalCell),
    PublishTerminalEvent(PublishTerminalEvent),
}

pub type RunTerminalCell = TerminalCellCommand;

pub type PublishTerminalEvent = TerminalEvent;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalEvent {
    SessionStarted(SessionStarted),
    PromptPatternReady(PromptPatternReady),
    GateReady(GateReady),
    InjectionWritten(InjectionWritten),
    TranscriptReady(TranscriptReady),
}

pub type SessionStarted = SessionResolution;

pub type PromptPatternReady = PromptPatternRegistration;

pub type GateReady = InputGateLease;

pub type InjectionWritten = InjectionReceipt;

pub type TranscriptReady = TranscriptCapture;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    CellSucceeded(CellSucceeded),
    CellFailed(CellFailed),
}

pub type CellSucceeded = TerminalEvent;

pub type CellFailed = ErrorReport;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    MetaArrived(MetaArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

impl NexusWork {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn meta_arrived(payload: MetaArrived) -> Self {
        Self::MetaArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl NexusAction {
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

impl SessionLifecycleCommand {
    pub fn create_session(payload: CreateSession) -> Self {
        Self::CreateSession(payload)
    }
    pub fn retire_session(payload: RetireSession) -> Self {
        Self::RetireSession(payload)
    }
}

impl TerminalCellCommand {
    pub fn start_session(payload: StartSession) -> Self {
        Self::StartSession(payload)
    }
    pub fn register_prompt_pattern(payload: RegisterPromptPattern) -> Self {
        Self::RegisterPromptPattern(payload)
    }
    pub fn acquire_input_gate(payload: AcquireInputGate) -> Self {
        Self::AcquireInputGate(payload)
    }
    pub fn write_injection(payload: WriteInjection) -> Self {
        Self::WriteInjection(payload)
    }
    pub fn release_input_gate(payload: ReleaseInputGate) -> Self {
        Self::ReleaseInputGate(payload)
    }
    pub fn capture_transcript(payload: CaptureTranscript) -> Self {
        Self::CaptureTranscript(payload)
    }
}

impl NexusEffectCommand {
    pub fn run_terminal_cell(payload: RunTerminalCell) -> Self {
        Self::RunTerminalCell(payload)
    }
    pub fn publish_terminal_event(payload: PublishTerminalEvent) -> Self {
        Self::PublishTerminalEvent(payload)
    }
}

impl TerminalEvent {
    pub fn session_started(payload: SessionStarted) -> Self {
        Self::SessionStarted(payload)
    }
    pub fn prompt_pattern_ready(payload: PromptPatternReady) -> Self {
        Self::PromptPatternReady(payload)
    }
    pub fn gate_ready(payload: GateReady) -> Self {
        Self::GateReady(payload)
    }
    pub fn injection_written(payload: InjectionWritten) -> Self {
        Self::InjectionWritten(payload)
    }
    pub fn transcript_ready(payload: TranscriptReady) -> Self {
        Self::TranscriptReady(payload)
    }
}

impl NexusEffectResult {
    pub fn cell_succeeded(payload: CellSucceeded) -> Self {
        Self::CellSucceeded(payload)
    }
    pub fn cell_failed(payload: CellFailed) -> Self {
        Self::CellFailed(payload)
    }
}

impl Input {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn meta_arrived(payload: MetaArrived) -> Self {
        Self::MetaArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl Output {
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SessionLifecycleCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl TerminalCellCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl TerminalEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    MetaArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::MetaArrived(_) => NexusWorkRoute::MetaArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    Continue,
}

impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::MetaArrived => "NexusWorkMetaArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl triad_runtime::NexusWork for NexusWork {}

impl triad_runtime::NexusEffectCommand for CommandEffect {}

impl triad_runtime::NexusEffectResult for EffectCompleted {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "actor resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "actor configuration invalid: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStartFailure {}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "actor resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "actor child still running: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStopFailure {}

pub type NexusRunnerNextStep = triad_runtime::NextStep<
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    NexusWork,
>;
impl triad_runtime::NexusAction for NexusAction {
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }
    fn apply_sema_write(
        &mut self,
        origin_route: OriginRoute,
        input: CommandSemaWrite,
    ) -> SemaWriteCompleted;
    fn observe_sema_read(
        &self,
        origin_route: OriginRoute,
        input: CommandSemaRead,
    ) -> SemaReadCompleted;
    fn run_effect(&mut self, input: CommandEffect) -> EffectCompleted;
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> ReplyToSignal;
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>
    where
        Self: Sized,
    {
        self.trace_nexus_entered();
        let origin_route = input.origin_route();
        let first_work = input.into_root();
        let runner = triad_runtime::Runner::new(self.continuation_limit());
        let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
        let reply = runner.drive(&mut runner_adapter, first_work);
        let output = NexusAction::reply_to_signal(reply).with_origin_route(origin_route);
        self.trace_nexus_decided();
        output
    }
}

struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}
impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}
impl<'engine, Engine> triad_runtime::RunnerEngines
for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn decide_next_step(
        &mut self,
        work: Self::Work,
    ) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(
                self.engine,
                work.with_origin_route(self.origin_route),
            )
            .into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }
    fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteCompleted = NexusEngine::apply_sema_write(
            self.engine,
            self.origin_route,
            write,
        );
        NexusWork::sema_write_completed(output)
    }
    fn observe_sema_read(&self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadCompleted = NexusEngine::observe_sema_read(
            self.engine,
            self.origin_route,
            read,
        );
        NexusWork::sema_read_completed(output)
    }
    fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: EffectCompleted = NexusEngine::run_effect(self.engine, effect);
        NexusWork::effect_completed(output)
    }
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
