// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::signal::SessionName as SessionName;
#[rustfmt::skip]
pub use crate::schema::signal::SessionRecord as SessionRecord;
#[rustfmt::skip]
pub use crate::schema::signal::SessionResolution as SessionResolution;
#[rustfmt::skip]
pub use crate::schema::signal::PromptPatternRegistration as PromptPatternRegistration;
#[rustfmt::skip]
pub use crate::schema::signal::InputGateLease as InputGateLease;
#[rustfmt::skip]
pub use crate::schema::signal::InjectionReceipt as InjectionReceipt;
#[rustfmt::skip]
pub use crate::schema::signal::TranscriptCapture as TranscriptCapture;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaArrived(SessionLifecycleCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectCompleted(NexusEffectResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaWrite(SemaWriteInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandEffect(NexusEffectCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    MetaArrived(MetaArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SessionLifecycleCommand {
    CreateSession(CreateSession),
    RetireSession(RetireSession),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CreateSession(SessionRecord);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireSession(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalCellCommand {
    StartSession(StartSession),
    RegisterPromptPattern(RegisterPromptPattern),
    AcquireInputGate(AcquireInputGate),
    WriteInjection(WriteInjection),
    ReleaseInputGate(ReleaseInputGate),
    CaptureTranscript(CaptureTranscript),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StartSession(SessionRecord);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterPromptPattern(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcquireInputGate(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WriteInjection(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseInputGate(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureTranscript(SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    RunTerminalCell(RunTerminalCell),
    PublishTerminalEvent(PublishTerminalEvent),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RunTerminalCell(TerminalCellCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublishTerminalEvent(TerminalEvent);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalEvent {
    SessionStarted(SessionStarted),
    PromptPatternReady(PromptPatternReady),
    GateReady(GateReady),
    InjectionWritten(InjectionWritten),
    TranscriptReady(TranscriptReady),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionStarted(SessionResolution);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternReady(PromptPatternRegistration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GateReady(InputGateLease);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InjectionWritten(InjectionReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TranscriptReady(TranscriptCapture);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    CellSucceeded(CellSucceeded),
    CellFailed(CellFailed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CellSucceeded(TerminalEvent);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CellFailed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    MetaArrived(MetaArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaArrived {
    pub fn new(payload: SessionLifecycleCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionLifecycleCommand {
        &self.0
    }
    pub fn into_payload(self) -> SessionLifecycleCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionLifecycleCommand> for MetaArrived {
    fn from(payload: SessionLifecycleCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EffectCompleted {
    pub fn new(payload: NexusEffectResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectResult {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectResult> for EffectCompleted {
    fn from(payload: NexusEffectResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn new(payload: SemaWriteInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteInput> for CommandSemaWrite {
    fn from(payload: SemaWriteInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandEffect {
    pub fn new(payload: NexusEffectCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectCommand {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectCommand> for CommandEffect {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CreateSession {
    pub fn new(payload: SessionRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionRecord {
        &self.0
    }
    pub fn into_payload(self) -> SessionRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionRecord> for CreateSession {
    fn from(payload: SessionRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireSession {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for RetireSession {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StartSession {
    pub fn new(payload: SessionRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionRecord {
        &self.0
    }
    pub fn into_payload(self) -> SessionRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionRecord> for StartSession {
    fn from(payload: SessionRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterPromptPattern {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for RegisterPromptPattern {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AcquireInputGate {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for AcquireInputGate {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WriteInjection {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for WriteInjection {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReleaseInputGate {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for ReleaseInputGate {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureTranscript {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for CaptureTranscript {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RunTerminalCell {
    pub fn new(payload: TerminalCellCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalCellCommand {
        &self.0
    }
    pub fn into_payload(self) -> TerminalCellCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalCellCommand> for RunTerminalCell {
    fn from(payload: TerminalCellCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PublishTerminalEvent {
    pub fn new(payload: TerminalEvent) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalEvent {
        &self.0
    }
    pub fn into_payload(self) -> TerminalEvent {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalEvent> for PublishTerminalEvent {
    fn from(payload: TerminalEvent) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SessionStarted {
    pub fn new(payload: SessionResolution) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionResolution {
        &self.0
    }
    pub fn into_payload(self) -> SessionResolution {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionResolution> for SessionStarted {
    fn from(payload: SessionResolution) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptPatternReady {
    pub fn new(payload: PromptPatternRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PromptPatternRegistration {
        &self.0
    }
    pub fn into_payload(self) -> PromptPatternRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<PromptPatternRegistration> for PromptPatternReady {
    fn from(payload: PromptPatternRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GateReady {
    pub fn new(payload: InputGateLease) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InputGateLease {
        &self.0
    }
    pub fn into_payload(self) -> InputGateLease {
        self.0
    }
}
#[rustfmt::skip]
impl From<InputGateLease> for GateReady {
    fn from(payload: InputGateLease) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InjectionWritten {
    pub fn new(payload: InjectionReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InjectionReceipt {
        &self.0
    }
    pub fn into_payload(self) -> InjectionReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<InjectionReceipt> for InjectionWritten {
    fn from(payload: InjectionReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TranscriptReady {
    pub fn new(payload: TranscriptCapture) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TranscriptCapture {
        &self.0
    }
    pub fn into_payload(self) -> TranscriptCapture {
        self.0
    }
}
#[rustfmt::skip]
impl From<TranscriptCapture> for TranscriptReady {
    fn from(payload: TranscriptCapture) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CellSucceeded {
    pub fn new(payload: TerminalEvent) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalEvent {
        &self.0
    }
    pub fn into_payload(self) -> TerminalEvent {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalEvent> for CellSucceeded {
    fn from(payload: TerminalEvent) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CellFailed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for CellFailed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn meta_arrived(payload: SessionLifecycleCommand) -> Self {
        Self::MetaArrived(MetaArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl SessionLifecycleCommand {
    pub fn create_session(payload: SessionRecord) -> Self {
        Self::CreateSession(CreateSession::new(payload))
    }
    pub fn retire_session(payload: SessionName) -> Self {
        Self::RetireSession(RetireSession::new(payload))
    }
}

#[rustfmt::skip]
impl TerminalCellCommand {
    pub fn start_session(payload: SessionRecord) -> Self {
        Self::StartSession(StartSession::new(payload))
    }
    pub fn register_prompt_pattern(payload: SessionName) -> Self {
        Self::RegisterPromptPattern(RegisterPromptPattern::new(payload))
    }
    pub fn acquire_input_gate(payload: SessionName) -> Self {
        Self::AcquireInputGate(AcquireInputGate::new(payload))
    }
    pub fn write_injection(payload: SessionName) -> Self {
        Self::WriteInjection(WriteInjection::new(payload))
    }
    pub fn release_input_gate(payload: SessionName) -> Self {
        Self::ReleaseInputGate(ReleaseInputGate::new(payload))
    }
    pub fn capture_transcript(payload: SessionName) -> Self {
        Self::CaptureTranscript(CaptureTranscript::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn run_terminal_cell(payload: TerminalCellCommand) -> Self {
        Self::RunTerminalCell(RunTerminalCell::new(payload))
    }
    pub fn publish_terminal_event(payload: TerminalEvent) -> Self {
        Self::PublishTerminalEvent(PublishTerminalEvent::new(payload))
    }
}

#[rustfmt::skip]
impl TerminalEvent {
    pub fn session_started(payload: SessionResolution) -> Self {
        Self::SessionStarted(SessionStarted::new(payload))
    }
    pub fn prompt_pattern_ready(payload: PromptPatternRegistration) -> Self {
        Self::PromptPatternReady(PromptPatternReady::new(payload))
    }
    pub fn gate_ready(payload: InputGateLease) -> Self {
        Self::GateReady(GateReady::new(payload))
    }
    pub fn injection_written(payload: InjectionReceipt) -> Self {
        Self::InjectionWritten(InjectionWritten::new(payload))
    }
    pub fn transcript_ready(payload: TranscriptCapture) -> Self {
        Self::TranscriptReady(TranscriptReady::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn cell_succeeded(payload: TerminalEvent) -> Self {
        Self::CellSucceeded(CellSucceeded::new(payload))
    }
    pub fn cell_failed(payload: ErrorReport) -> Self {
        Self::CellFailed(CellFailed::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn meta_arrived(payload: SessionLifecycleCommand) -> Self {
        Self::MetaArrived(MetaArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<MetaArrived> for NexusWork {
    fn from(payload: MetaArrived) -> Self {
        Self::MetaArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusWork {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusWork {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for NexusWork {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusAction {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusAction {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for NexusAction {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<CreateSession> for SessionLifecycleCommand {
    fn from(payload: CreateSession) -> Self {
        Self::CreateSession(payload)
    }
}

#[rustfmt::skip]
impl From<RetireSession> for SessionLifecycleCommand {
    fn from(payload: RetireSession) -> Self {
        Self::RetireSession(payload)
    }
}

#[rustfmt::skip]
impl From<StartSession> for TerminalCellCommand {
    fn from(payload: StartSession) -> Self {
        Self::StartSession(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterPromptPattern> for TerminalCellCommand {
    fn from(payload: RegisterPromptPattern) -> Self {
        Self::RegisterPromptPattern(payload)
    }
}

#[rustfmt::skip]
impl From<AcquireInputGate> for TerminalCellCommand {
    fn from(payload: AcquireInputGate) -> Self {
        Self::AcquireInputGate(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInjection> for TerminalCellCommand {
    fn from(payload: WriteInjection) -> Self {
        Self::WriteInjection(payload)
    }
}

#[rustfmt::skip]
impl From<ReleaseInputGate> for TerminalCellCommand {
    fn from(payload: ReleaseInputGate) -> Self {
        Self::ReleaseInputGate(payload)
    }
}

#[rustfmt::skip]
impl From<CaptureTranscript> for TerminalCellCommand {
    fn from(payload: CaptureTranscript) -> Self {
        Self::CaptureTranscript(payload)
    }
}

#[rustfmt::skip]
impl From<RunTerminalCell> for NexusEffectCommand {
    fn from(payload: RunTerminalCell) -> Self {
        Self::RunTerminalCell(payload)
    }
}

#[rustfmt::skip]
impl From<PublishTerminalEvent> for NexusEffectCommand {
    fn from(payload: PublishTerminalEvent) -> Self {
        Self::PublishTerminalEvent(payload)
    }
}

#[rustfmt::skip]
impl From<SessionStarted> for TerminalEvent {
    fn from(payload: SessionStarted) -> Self {
        Self::SessionStarted(payload)
    }
}

#[rustfmt::skip]
impl From<PromptPatternReady> for TerminalEvent {
    fn from(payload: PromptPatternReady) -> Self {
        Self::PromptPatternReady(payload)
    }
}

#[rustfmt::skip]
impl From<GateReady> for TerminalEvent {
    fn from(payload: GateReady) -> Self {
        Self::GateReady(payload)
    }
}

#[rustfmt::skip]
impl From<InjectionWritten> for TerminalEvent {
    fn from(payload: InjectionWritten) -> Self {
        Self::InjectionWritten(payload)
    }
}

#[rustfmt::skip]
impl From<TranscriptReady> for TerminalEvent {
    fn from(payload: TranscriptReady) -> Self {
        Self::TranscriptReady(payload)
    }
}

#[rustfmt::skip]
impl From<CellSucceeded> for NexusEffectResult {
    fn from(payload: CellSucceeded) -> Self {
        Self::CellSucceeded(payload)
    }
}

#[rustfmt::skip]
impl From<CellFailed> for NexusEffectResult {
    fn from(payload: CellFailed) -> Self {
        Self::CellFailed(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<MetaArrived> for Input {
    fn from(payload: MetaArrived) -> Self {
        Self::MetaArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for Input {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for Input {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for Input {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for Output {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for Output {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for Output {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    MetaArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::MetaArrived(_) => NexusWorkRoute::MetaArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::MetaArrived => "NexusWorkMetaArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
