// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use crate::schema::signal::SessionName as SessionName;
pub use crate::schema::signal::SessionRecord as SessionRecord;
pub use crate::schema::signal::PromptPatternRegistration as PromptPatternRegistration;
pub use crate::schema::signal::InputGateLease as InputGateLease;
pub use crate::schema::signal::InjectionReceipt as InjectionReceipt;
pub use crate::schema::signal::TranscriptCapture as TranscriptCapture;
pub use crate::schema::signal::ErrorReport as ErrorReport;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    RecordSession(RecordSession),
    RetireSession(RetireSession),
    RecordPromptPattern(RecordPromptPattern),
    RecordInputGate(RecordInputGate),
    RecordInjection(RecordInjection),
}

pub type RecordSession = SessionRecord;

pub type RetireSession = SessionName;

pub type RecordPromptPattern = PromptPatternRegistration;

pub type RecordInputGate = InputGateLease;

pub type RecordInjection = InjectionReceipt;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    ListSessionRecords(ListSessionRecords),
    ResolveSessionRecord(ResolveSessionRecord),
    ReadTranscript(ReadTranscript),
}

pub type ListSessionRecords = ListSessionsMarker;

pub type ResolveSessionRecord = SessionName;

pub type ReadTranscript = SessionName;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    Committed(CommitReceipt),
    WriteRejected(ErrorReport),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    SessionRecordsRead(SessionRecordsRead),
    SessionRecordResolved(SessionRecordResolved),
    TranscriptRead(TranscriptRead),
    ReadRejected(ErrorReport),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListSessionsMarker {}

pub type CommitSequence = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitReceipt(pub CommitSequence);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionRecordsRead(pub CommitSequence);

pub type SessionRecordResolved = SessionRecord;

pub type TranscriptRead = TranscriptCapture;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WriteInput(WriteInput),
    ReadInput(ReadInput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    WriteOutput(WriteOutput),
    ReadOutput(ReadOutput),
}

impl CommitReceipt {
    pub fn new(payload: CommitSequence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CommitSequence {
        &self.0
    }
    pub fn into_payload(self) -> CommitSequence {
        self.0
    }
}
impl From<CommitSequence> for CommitReceipt {
    fn from(payload: CommitSequence) -> Self {
        Self::new(payload)
    }
}

impl SessionRecordsRead {
    pub fn new(payload: CommitSequence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CommitSequence {
        &self.0
    }
    pub fn into_payload(self) -> CommitSequence {
        self.0
    }
}
impl From<CommitSequence> for SessionRecordsRead {
    fn from(payload: CommitSequence) -> Self {
        Self::new(payload)
    }
}

impl WriteInput {
    pub fn record_session(payload: RecordSession) -> Self {
        Self::RecordSession(payload)
    }
    pub fn retire_session(payload: RetireSession) -> Self {
        Self::RetireSession(payload)
    }
    pub fn record_prompt_pattern(payload: RecordPromptPattern) -> Self {
        Self::RecordPromptPattern(payload)
    }
    pub fn record_input_gate(payload: RecordInputGate) -> Self {
        Self::RecordInputGate(payload)
    }
    pub fn record_injection(payload: RecordInjection) -> Self {
        Self::RecordInjection(payload)
    }
}

impl ReadInput {
    pub fn list_session_records(payload: ListSessionRecords) -> Self {
        Self::ListSessionRecords(payload)
    }
    pub fn resolve_session_record(payload: ResolveSessionRecord) -> Self {
        Self::ResolveSessionRecord(payload)
    }
    pub fn read_transcript(payload: ReadTranscript) -> Self {
        Self::ReadTranscript(payload)
    }
}

impl WriteOutput {
    pub fn committed(payload: CommitSequence) -> Self {
        Self::Committed(CommitReceipt::new(payload))
    }
    pub fn write_rejected(payload: ErrorReport) -> Self {
        Self::WriteRejected(payload)
    }
}

impl ReadOutput {
    pub fn session_records_read(payload: CommitSequence) -> Self {
        Self::SessionRecordsRead(SessionRecordsRead::new(payload))
    }
    pub fn session_record_resolved(payload: SessionRecordResolved) -> Self {
        Self::SessionRecordResolved(payload)
    }
    pub fn transcript_read(payload: TranscriptRead) -> Self {
        Self::TranscriptRead(payload)
    }
    pub fn read_rejected(payload: ErrorReport) -> Self {
        Self::ReadRejected(payload)
    }
}

impl Input {
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

impl Output {
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

impl From<CommitReceipt> for WriteOutput {
    fn from(payload: CommitReceipt) -> Self {
        Self::Committed(payload)
    }
}

impl From<ErrorReport> for WriteOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::WriteRejected(payload)
    }
}

impl From<SessionRecordsRead> for ReadOutput {
    fn from(payload: SessionRecordsRead) -> Self {
        Self::SessionRecordsRead(payload)
    }
}

impl From<ErrorReport> for ReadOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::ReadRejected(payload)
    }
}

impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[cfg(feature = "nota-text")]
impl WriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl WriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ListSessionsMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CommitReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SessionRecordsRead {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    RecordSession,
    RetireSession,
    RecordPromptPattern,
    RecordInputGate,
    RecordInjection,
}

impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::RecordSession(_) => WriteInputRoute::RecordSession,
            Self::RetireSession(_) => WriteInputRoute::RetireSession,
            Self::RecordPromptPattern(_) => WriteInputRoute::RecordPromptPattern,
            Self::RecordInputGate(_) => WriteInputRoute::RecordInputGate,
            Self::RecordInjection(_) => WriteInputRoute::RecordInjection,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    ListSessionRecords,
    ResolveSessionRecord,
    ReadTranscript,
}

impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::ListSessionRecords(_) => ReadInputRoute::ListSessionRecords,
            Self::ResolveSessionRecord(_) => ReadInputRoute::ResolveSessionRecord,
            Self::ReadTranscript(_) => ReadInputRoute::ReadTranscript,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    Committed,
    WriteRejected,
}

impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::Committed(_) => WriteOutputRoute::Committed,
            Self::WriteRejected(_) => WriteOutputRoute::WriteRejected,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    SessionRecordsRead,
    SessionRecordResolved,
    TranscriptRead,
    ReadRejected,
}

impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::SessionRecordsRead(_) => ReadOutputRoute::SessionRecordsRead,
            Self::SessionRecordResolved(_) => ReadOutputRoute::SessionRecordResolved,
            Self::TranscriptRead(_) => ReadOutputRoute::TranscriptRead,
            Self::ReadRejected(_) => ReadOutputRoute::ReadRejected,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::RecordSession => "SemaWriteInputRecordSession",
                    WriteInputRoute::RetireSession => "SemaWriteInputRetireSession",
                    WriteInputRoute::RecordPromptPattern => {
                        "SemaWriteInputRecordPromptPattern"
                    }
                    WriteInputRoute::RecordInputGate => "SemaWriteInputRecordInputGate",
                    WriteInputRoute::RecordInjection => "SemaWriteInputRecordInjection",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::ListSessionRecords => {
                        "SemaReadInputListSessionRecords"
                    }
                    ReadInputRoute::ResolveSessionRecord => {
                        "SemaReadInputResolveSessionRecord"
                    }
                    ReadInputRoute::ReadTranscript => "SemaReadInputReadTranscript",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::Committed => "SemaWriteOutputCommitted",
                    WriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::SessionRecordsRead => {
                        "SemaReadOutputSessionRecordsRead"
                    }
                    ReadOutputRoute::SessionRecordResolved => {
                        "SemaReadOutputSessionRecordResolved"
                    }
                    ReadOutputRoute::TranscriptRead => "SemaReadOutputTranscriptRead",
                    ReadOutputRoute::ReadRejected => "SemaReadOutputReadRejected",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl triad_runtime::SemaWriteInput for WriteInput {}

impl triad_runtime::SemaWriteOutput for WriteOutput {}

impl triad_runtime::SemaReadInput for ReadInput {}

impl triad_runtime::SemaReadOutput for ReadOutput {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "actor resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "actor configuration invalid: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStartFailure {}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "actor resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "actor child still running: {message}")
            }
        }
    }
}
impl std::error::Error for ActorStopFailure {}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
