// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type ListSessions = ListSessionsRequest;

#[rustfmt::skip]
pub type ResolveSession = ResolveSessionRequest;

#[rustfmt::skip]
pub type RegisterPromptPattern = RegisterPromptPatternRequest;

#[rustfmt::skip]
pub type AcquireInputGate = AcquireInputGateRequest;

#[rustfmt::skip]
pub type WriteInjection = WriteInjectionRequest;

#[rustfmt::skip]
pub type ReleaseInputGate = ReleaseInputGateRequest;

#[rustfmt::skip]
pub type CaptureTranscript = CaptureTranscriptRequest;

#[rustfmt::skip]
pub type SessionsListed = SessionList;

#[rustfmt::skip]
pub type SessionResolved = SessionResolution;

#[rustfmt::skip]
pub type PromptPatternRegistered = PromptPatternRegistration;

#[rustfmt::skip]
pub type InputGateAcquired = InputGateLease;

#[rustfmt::skip]
pub type InjectionAcknowledged = InjectionReceipt;

#[rustfmt::skip]
pub type InputGateReleased = InputGateReleaseReceipt;

#[rustfmt::skip]
pub type TranscriptCaptured = TranscriptCapture;

#[rustfmt::skip]
pub type Unimplemented = RequestUnimplemented;

#[rustfmt::skip]
pub type Error = ErrorReport;

#[rustfmt::skip]
pub type SessionName = String;

#[rustfmt::skip]
pub type SessionIdentifier = Integer;

#[rustfmt::skip]
pub type PromptPatternIdentifier = Integer;

#[rustfmt::skip]
pub type InputLeaseIdentifier = Integer;

#[rustfmt::skip]
pub type InjectionSequence = Integer;

#[rustfmt::skip]
pub type TranscriptSequence = Integer;

#[rustfmt::skip]
pub type TerminalByte = Integer;

#[rustfmt::skip]
pub type TerminalBytes = Vec<TerminalByte>;

#[rustfmt::skip]
pub type SocketPath = Path;

#[rustfmt::skip]
pub type ErrorMessage = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListSessionsRequest {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolveSessionRequest(pub SessionName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterPromptPatternRequest {
    pub session_name: SessionName,
    pub prompt_pattern_text: PromptPatternText,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcquireInputGateRequest {
    pub session_name: SessionName,
    pub prompt_pattern_identifier: PromptPatternIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WriteInjectionRequest {
    pub session_name: SessionName,
    pub input_lease_identifier: InputLeaseIdentifier,
    pub injection_sequence: InjectionSequence,
    pub terminal_bytes: TerminalBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseInputGateRequest {
    pub session_name: SessionName,
    pub input_lease_identifier: InputLeaseIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CaptureTranscriptRequest(pub SessionName);

#[rustfmt::skip]
pub type PromptPatternText = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionRecord {
    pub session_name: SessionName,
    pub session_identifier: SessionIdentifier,
    pub socket_path: SocketPath,
}

#[rustfmt::skip]
pub type SessionRecords = Vec<SessionRecord>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionList(pub SessionRecords);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionResolution(pub SessionRecord);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternRegistration(pub PromptPatternIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PromptState {
    Clean,
    Dirty,
    NotChecked,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InputGateLease {
    pub input_lease_identifier: InputLeaseIdentifier,
    pub prompt_state: PromptState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InjectionReceipt(pub InjectionSequence);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InputGateReleaseReceipt(pub InputLeaseIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TranscriptCapture {
    pub transcript_sequence: TranscriptSequence,
    pub terminal_bytes: TerminalBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    ListSessions,
    ResolveSession,
    RegisterPromptPattern,
    AcquireInputGate,
    WriteInjection,
    ReleaseInputGate,
    CaptureTranscript,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
    SessionMissing,
    LeaseMissing,
    DirtyPrompt,
    CellUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub operation_kind: OperationKind,
    pub unimplemented_reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport(pub ErrorMessage);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ListSessions(ListSessions),
    ResolveSession(ResolveSession),
    RegisterPromptPattern(RegisterPromptPattern),
    AcquireInputGate(AcquireInputGate),
    WriteInjection(WriteInjection),
    ReleaseInputGate(ReleaseInputGate),
    CaptureTranscript(CaptureTranscript),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SessionsListed(SessionsListed),
    SessionResolved(SessionResolved),
    PromptPatternRegistered(PromptPatternRegistered),
    InputGateAcquired(InputGateAcquired),
    InjectionAcknowledged(InjectionAcknowledged),
    InputGateReleased(InputGateReleased),
    TranscriptCaptured(TranscriptCaptured),
    Unimplemented(Unimplemented),
    Error(Error),
}

#[rustfmt::skip]
impl ResolveSessionRequest {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for ResolveSessionRequest {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CaptureTranscriptRequest {
    pub fn new(payload: SessionName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionName {
        &self.0
    }
    pub fn into_payload(self) -> SessionName {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionName> for CaptureTranscriptRequest {
    fn from(payload: SessionName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SessionList {
    pub fn new(payload: SessionRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionRecords {
        &self.0
    }
    pub fn into_payload(self) -> SessionRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionRecords> for SessionList {
    fn from(payload: SessionRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SessionResolution {
    pub fn new(payload: SessionRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SessionRecord {
        &self.0
    }
    pub fn into_payload(self) -> SessionRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<SessionRecord> for SessionResolution {
    fn from(payload: SessionRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptPatternRegistration {
    pub fn new(payload: PromptPatternIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PromptPatternIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PromptPatternIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PromptPatternIdentifier> for PromptPatternRegistration {
    fn from(payload: PromptPatternIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InjectionReceipt {
    pub fn new(payload: InjectionSequence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InjectionSequence {
        &self.0
    }
    pub fn into_payload(self) -> InjectionSequence {
        self.0
    }
}
#[rustfmt::skip]
impl From<InjectionSequence> for InjectionReceipt {
    fn from(payload: InjectionSequence) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InputGateReleaseReceipt {
    pub fn new(payload: InputLeaseIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InputLeaseIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> InputLeaseIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<InputLeaseIdentifier> for InputGateReleaseReceipt {
    fn from(payload: InputLeaseIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorReport {
    pub fn new(payload: ErrorMessage) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorMessage {
        &self.0
    }
    pub fn into_payload(self) -> ErrorMessage {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorMessage> for ErrorReport {
    fn from(payload: ErrorMessage) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn list_sessions(payload: ListSessions) -> Self {
        Self::ListSessions(payload)
    }
    pub fn resolve_session(payload: ResolveSession) -> Self {
        Self::ResolveSession(payload)
    }
    pub fn register_prompt_pattern(payload: RegisterPromptPattern) -> Self {
        Self::RegisterPromptPattern(payload)
    }
    pub fn acquire_input_gate(payload: AcquireInputGate) -> Self {
        Self::AcquireInputGate(payload)
    }
    pub fn write_injection(payload: WriteInjection) -> Self {
        Self::WriteInjection(payload)
    }
    pub fn release_input_gate(payload: ReleaseInputGate) -> Self {
        Self::ReleaseInputGate(payload)
    }
    pub fn capture_transcript(payload: CaptureTranscript) -> Self {
        Self::CaptureTranscript(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sessions_listed(payload: SessionsListed) -> Self {
        Self::SessionsListed(payload)
    }
    pub fn session_resolved(payload: SessionResolved) -> Self {
        Self::SessionResolved(payload)
    }
    pub fn prompt_pattern_registered(payload: PromptPatternRegistered) -> Self {
        Self::PromptPatternRegistered(payload)
    }
    pub fn input_gate_acquired(payload: InputGateAcquired) -> Self {
        Self::InputGateAcquired(payload)
    }
    pub fn injection_acknowledged(payload: InjectionAcknowledged) -> Self {
        Self::InjectionAcknowledged(payload)
    }
    pub fn input_gate_released(payload: InputGateReleased) -> Self {
        Self::InputGateReleased(payload)
    }
    pub fn transcript_captured(payload: TranscriptCaptured) -> Self {
        Self::TranscriptCaptured(payload)
    }
    pub fn unimplemented(payload: Unimplemented) -> Self {
        Self::Unimplemented(payload)
    }
    pub fn error(payload: Error) -> Self {
        Self::Error(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ListSessionsRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ResolveSessionRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RegisterPromptPatternRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AcquireInputGateRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteInjectionRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReleaseInputGateRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CaptureTranscriptRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionList {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionResolution {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternRegistration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InputGateLease {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InjectionReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InputGateReleaseReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TranscriptCapture {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ErrorReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_LIST_SESSIONS: u64 = 0x0000000000000000;
    pub const INPUT_RESOLVE_SESSION: u64 = 0x0001000000000000;
    pub const INPUT_REGISTER_PROMPT_PATTERN: u64 = 0x0002000000000000;
    pub const INPUT_ACQUIRE_INPUT_GATE: u64 = 0x0003000000000000;
    pub const INPUT_WRITE_INJECTION: u64 = 0x0004000000000000;
    pub const INPUT_RELEASE_INPUT_GATE: u64 = 0x0005000000000000;
    pub const INPUT_CAPTURE_TRANSCRIPT: u64 = 0x0006000000000000;
    pub const OUTPUT_SESSIONS_LISTED: u64 = 0x0100000000000000;
    pub const OUTPUT_SESSION_RESOLVED: u64 = 0x0101000000000000;
    pub const OUTPUT_PROMPT_PATTERN_REGISTERED: u64 = 0x0102000000000000;
    pub const OUTPUT_INPUT_GATE_ACQUIRED: u64 = 0x0103000000000000;
    pub const OUTPUT_INJECTION_ACKNOWLEDGED: u64 = 0x0104000000000000;
    pub const OUTPUT_INPUT_GATE_RELEASED: u64 = 0x0105000000000000;
    pub const OUTPUT_TRANSCRIPT_CAPTURED: u64 = 0x0106000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0107000000000000;
    pub const OUTPUT_ERROR: u64 = 0x0108000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    ListSessions,
    ResolveSession,
    RegisterPromptPattern,
    AcquireInputGate,
    WriteInjection,
    ReleaseInputGate,
    CaptureTranscript,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SessionsListed,
    SessionResolved,
    PromptPatternRegistered,
    InputGateAcquired,
    InjectionAcknowledged,
    InputGateReleased,
    TranscriptCaptured,
    Unimplemented,
    Error,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::ListSessions(_) => InputRoute::ListSessions,
            Self::ResolveSession(_) => InputRoute::ResolveSession,
            Self::RegisterPromptPattern(_) => InputRoute::RegisterPromptPattern,
            Self::AcquireInputGate(_) => InputRoute::AcquireInputGate,
            Self::WriteInjection(_) => InputRoute::WriteInjection,
            Self::ReleaseInputGate(_) => InputRoute::ReleaseInputGate,
            Self::CaptureTranscript(_) => InputRoute::CaptureTranscript,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ListSessions(_) => short_header::INPUT_LIST_SESSIONS,
            Self::ResolveSession(_) => short_header::INPUT_RESOLVE_SESSION,
            Self::RegisterPromptPattern(_) => short_header::INPUT_REGISTER_PROMPT_PATTERN,
            Self::AcquireInputGate(_) => short_header::INPUT_ACQUIRE_INPUT_GATE,
            Self::WriteInjection(_) => short_header::INPUT_WRITE_INJECTION,
            Self::ReleaseInputGate(_) => short_header::INPUT_RELEASE_INPUT_GATE,
            Self::CaptureTranscript(_) => short_header::INPUT_CAPTURE_TRANSCRIPT,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_LIST_SESSIONS => Ok(InputRoute::ListSessions),
            short_header::INPUT_RESOLVE_SESSION => Ok(InputRoute::ResolveSession),
            short_header::INPUT_REGISTER_PROMPT_PATTERN => {
                Ok(InputRoute::RegisterPromptPattern)
            }
            short_header::INPUT_ACQUIRE_INPUT_GATE => Ok(InputRoute::AcquireInputGate),
            short_header::INPUT_WRITE_INJECTION => Ok(InputRoute::WriteInjection),
            short_header::INPUT_RELEASE_INPUT_GATE => Ok(InputRoute::ReleaseInputGate),
            short_header::INPUT_CAPTURE_TRANSCRIPT => Ok(InputRoute::CaptureTranscript),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SessionsListed(_) => OutputRoute::SessionsListed,
            Self::SessionResolved(_) => OutputRoute::SessionResolved,
            Self::PromptPatternRegistered(_) => OutputRoute::PromptPatternRegistered,
            Self::InputGateAcquired(_) => OutputRoute::InputGateAcquired,
            Self::InjectionAcknowledged(_) => OutputRoute::InjectionAcknowledged,
            Self::InputGateReleased(_) => OutputRoute::InputGateReleased,
            Self::TranscriptCaptured(_) => OutputRoute::TranscriptCaptured,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
            Self::Error(_) => OutputRoute::Error,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SessionsListed(_) => short_header::OUTPUT_SESSIONS_LISTED,
            Self::SessionResolved(_) => short_header::OUTPUT_SESSION_RESOLVED,
            Self::PromptPatternRegistered(_) => {
                short_header::OUTPUT_PROMPT_PATTERN_REGISTERED
            }
            Self::InputGateAcquired(_) => short_header::OUTPUT_INPUT_GATE_ACQUIRED,
            Self::InjectionAcknowledged(_) => short_header::OUTPUT_INJECTION_ACKNOWLEDGED,
            Self::InputGateReleased(_) => short_header::OUTPUT_INPUT_GATE_RELEASED,
            Self::TranscriptCaptured(_) => short_header::OUTPUT_TRANSCRIPT_CAPTURED,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
            Self::Error(_) => short_header::OUTPUT_ERROR,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SESSIONS_LISTED => Ok(OutputRoute::SessionsListed),
            short_header::OUTPUT_SESSION_RESOLVED => Ok(OutputRoute::SessionResolved),
            short_header::OUTPUT_PROMPT_PATTERN_REGISTERED => {
                Ok(OutputRoute::PromptPatternRegistered)
            }
            short_header::OUTPUT_INPUT_GATE_ACQUIRED => {
                Ok(OutputRoute::InputGateAcquired)
            }
            short_header::OUTPUT_INJECTION_ACKNOWLEDGED => {
                Ok(OutputRoute::InjectionAcknowledged)
            }
            short_header::OUTPUT_INPUT_GATE_RELEASED => {
                Ok(OutputRoute::InputGateReleased)
            }
            short_header::OUTPUT_TRANSCRIPT_CAPTURED => {
                Ok(OutputRoute::TranscriptCaptured)
            }
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "ListSessions",
        "ResolveSession",
        "RegisterPromptPattern",
        "AcquireInputGate",
        "WriteInjection",
        "ReleaseInputGate",
        "CaptureTranscript",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}
#[rustfmt::skip]
impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => {
                match route {
                    InputRoute::ListSessions => "SignalInputListSessions",
                    InputRoute::ResolveSession => "SignalInputResolveSession",
                    InputRoute::RegisterPromptPattern => {
                        "SignalInputRegisterPromptPattern"
                    }
                    InputRoute::AcquireInputGate => "SignalInputAcquireInputGate",
                    InputRoute::WriteInjection => "SignalInputWriteInjection",
                    InputRoute::ReleaseInputGate => "SignalInputReleaseInputGate",
                    InputRoute::CaptureTranscript => "SignalInputCaptureTranscript",
                }
            }
            Self::Output(route) => {
                match route {
                    OutputRoute::SessionsListed => "SignalOutputSessionsListed",
                    OutputRoute::SessionResolved => "SignalOutputSessionResolved",
                    OutputRoute::PromptPatternRegistered => {
                        "SignalOutputPromptPatternRegistered"
                    }
                    OutputRoute::InputGateAcquired => "SignalOutputInputGateAcquired",
                    OutputRoute::InjectionAcknowledged => {
                        "SignalOutputInjectionAcknowledged"
                    }
                    OutputRoute::InputGateReleased => "SignalOutputInputGateReleased",
                    OutputRoute::TranscriptCaptured => "SignalOutputTranscriptCaptured",
                    OutputRoute::Unimplemented => "SignalOutputUnimplemented",
                    OutputRoute::Error => "SignalOutputError",
                }
            }
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Signal(SignalObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageRoot {
    Input,
    Output,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}
#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}
#[rustfmt::skip]
pub trait MessageSentHook {
    type Error;
    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
pub trait MessageProcessedHook<Reply> {
    type Error;
    fn message_processed(
        &mut self,
        event: MessageProcessed<Reply>,
    ) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}
#[rustfmt::skip]
impl<Reply> MessageProcessed<Reply> {
    pub fn new(
        identifier: MessageIdentifier,
        origin_route: OriginRoute,
        reply: Reply,
    ) -> Self {
        Self {
            identifier,
            origin_route,
            reply,
        }
    }
    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn into_reply(self) -> Reply {
        self.reply
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}
#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}
#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SignalEngine: Send {
    type NexusInput;
    type NexusOutput;
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }
    fn triage_inner(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput;
    fn reply_inner(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output>;
    fn triage(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }
    fn reply(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
